mod.web_list {
	allowedNewTables = tx_news_domain_model_category, tx_news_domain_model_file, tx_news_domain_model_link, tx_news_domain_model_media, tx_news_domain_model_news, tx_news_domain_model_tag
}